### ISSUE TITLE
Error when install from npm

### ISSUE THREAD

**Issue by ayxos** [danrouse/react-audio-recorder#7]
I dont know why i have the following error:

```
[2] [dev:server] /Users/Marco/projects/node-seed/node_modules/react-audio-recorder/lib/AudioRecorder.js:258
[2]   audio: _react.PropTypes.instanceOf(Blob),
[2]                                      ^
[2] [dev:server] ReferenceError: Blob is not defined
[2]     at Object.<anonymous> (/Users/Marco/projects/node-seed/node_modules/react-audio-recorder/lib/AudioRecorder.js:258:38)
[2]     at Module._compile (module.js:570:32)
```

**Comment by kinabalu** [comment]
Can you identify what version of npm, node, you're using? I've just installed it and it installed properly.
